### ISSUE TITLE
Ignore code comments

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/detect-indent#29]
Some code comments have a space index:

```php
/**
 * Comment
 *
 * @todo Moar.
 */
function() {
<tab>yah();

<tab>...

}
```

From: https://github.com/sindresorhus/detect-indent-cli/issues/3

**Comment by lkraav** [comment]
I think it makes sense to adjust algorithm to check 2+ space count only, like GNU stdlib `unexpand` does.

**Comment by sindresorhus** [comment]
@lkraav Good point: https://github.com/sindresorhus/detect-indent/issues/30

**Comment by brandon93s** [comment]
This could get complicated, even requiring language detection, to cover the [different comment syntaxes](https://en.wikipedia.org/wiki/Comment_(computer_programming)?oldformat=true#Examples) since this module isn't exclusive to JavaScript indent detection.  PR #31 is opened for the proposal in #30 which may be sufficient to satisfy this issue, too.

**Comment by sindresorhus** [comment]
Yeah. After thinking more about this, it would get very complicated as multi-line comments can be nested. Let's do #30 instead.
